name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

permissions:  
  contents: read
  pull-requests: write

jobs:
  auto-assign-creator:  # Job to assign the PR creator
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Assign PR Creator
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const creator = context.payload.pull_request.user.login;

            github.rest.issues.addAssignees({
                issue_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: [creator]
            });
