name: Auto Assign PR Reviewers

on:
  pull_request_target:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
    branches:
      - 'staging'
      - 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:

      - name: Clear Cache
        uses: actions/cache@v4.0.2
        with:
         path: |
           ./.github/workflows/
         key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-workflow-${{ github.event_name }}-             
                 
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4.1.6 # v4.1.6
        with:
          fetch-depth: 0 

      - name: Check if Reviewers Already Assigned
        uses: actions/github-script@v7.0.1 # v7.0.1
        id: check-reviewers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { requested_reviewers } } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const existingReviewers = requested_reviewers.map(reviewer => reviewer.login);
            const reviewersToAdd = ['GTCrais', 'CTLLaw'].filter(reviewer => !existingReviewers.includes(reviewer));

            return reviewersToAdd.length > 0 ? JSON.stringify(reviewersToAdd) : 'null';

      - name: Auto Assign Reviewers (if needed)
        if: steps.check-reviewers.outputs.result != 'null'
        uses: actions/github-script@v7.0.1 # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewersToAdd = JSON.parse(steps.check-reviewers.outputs.result);
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: reviewersToAdd
            });
            console.log(`Reviewers ${reviewersToAdd.join(', ')} successfully assigned.`);