name: Auto Assign PR Creator and Reviewers

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - '.github/workflows/auto-assign.yml'
      - '.github/PULL_REQUEST_TEMPLATE/pull_request_template.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Get Pull Request Template
        uses: actions/checkout@v4.1.6
        with:
          path: .github/PULL_REQUEST_TEMPLATE
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read PR Template
        id: read_template
        run: |
          echo "::set-output name=template::$(cat .github/PULL_REQUEST_TEMPLATE/pull_request_template.md)"

      - name: Auto Assign Reviewers
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const body = context.payload.pull_request.body || "";
            const template = github.context.outputs.template || "";
            const baseRef = context.payload.pull_request.base.ref;
            const creator = context.payload.pull_request.user.login;
            const reviewers = [];

            // Check for PR type (Application or Infrastructure) in the PR body or template
            const isApplicationsPR = body.toLowerCase().includes("[x] **applications**") || template.toLowerCase().includes("[x] **applications**");
            const isInfrastructurePR = body.toLowerCase().includes("[x] **infrastructure**") || template.toLowerCase().includes("[x] **infrastructure**");

            // Assign reviewers based on PR type and target branch
            if (isApplicationsPR) {
              reviewers.push("GTCrais");
              // Add additional reviewer based on PR type
              reviewers.push("additionalReviewerForApplications");
            }

            if (isInfrastructurePR) {
              reviewers.push("mbsimonovic");
              // PR creator checks it if it's an Infrastructure PR
              if (!body.toLowerCase().includes("[x] **infrastructure**")) {
                reviewers.push(creator);
              }
              // Add additional reviewer based on PR type
              reviewers.push("additionalReviewerForInfrastructure");
            }

            if (baseRef === "master") {
              reviewers.push("CTLLaw");
            }

            // Assign the reviewers
            if (reviewers.length > 0) {
              github.rest.pulls.requestReviewers({
                pull_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                reviewers: reviewers,
              });
            }

  auto-assign-creator:  # Assign PR creator (only if not already a reviewer)
    needs: auto_assign_reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Assign PR Creator
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const creator = context.payload.pull_request.user.login;
            const { data: { assignees } } = await github.rest.issues.get({
                issue_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
            });

            // Ensure the PR creator is not assigned already
            if (!assignees.map(assignee => assignee.login).includes(creator)) {
                github.rest.issues.addAssignees({
                    issue_number: pull_number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    assignees: [creator]
                });
            }
