name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Assign PR Creator
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const creator = context.payload.pull_request.user.login;

            github.rest.issues.addAssignees({
                issue_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: [creator]
            });
