name: Auto Assign PR Reviewers

on:
  # Trigger when a pull request is opened or reopened
  pull_request:
    types: [opened, reopened, ready_for_review] 
  # Trigger when a pull request's target branch changes
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign-reviewers:  # Job to assign reviewers based on PR type
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Auto Assign Reviewers
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const body = context.payload.pull_request.body || ""; 
            const baseRef = context.payload.pull_request.base.ref;
            const assignees = [];

            // Check for PR type (Application or Infrastructure)
            const isApplicationPR = body.toLowerCase().includes("applications");
            const isInfrastructurePR = body.toLowerCase().includes("infrastructure");

            // Assign reviewers based on PR type and target branch
            if (isApplicationPR) {
              assignees.push("GTCrais");
            }

            if (isInfrastructurePR) {
              assignees.push("mbsimonovic");
            }

            if (baseRef === "master") {
              assignees.push("CTLLaw"); 
            }

            // Assign the reviewers
            if (assignees.length > 0) {
              github.rest.issues.addAssignees({
                issue_number: pull_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: assignees,
              });
            }
