name: Auto Assign PR Reviewers

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize, converted_to_draft]
    branches:
      - 'staging'
      - 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0 # Fetch full git history to ensure accurate pull request context

      - name: Check if Reviewers Already Assigned
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: check-reviewers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { requested_reviewers } } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const existingReviewers = requested_reviewers.map(reviewer => reviewer.login);
            const reviewersToAdd = ['GTCrais', 'CTLLaw'].filter(reviewer => !existingReviewers.includes(reviewer));

            return reviewersToAdd.length > 0 ? reviewersToAdd : null; 

      - name: Auto Assign Reviewers (if needed)
        if: steps.check-reviewers.outputs.result != 'null'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewersToAdd = JSON.parse(steps.check-reviewers.outputs.result);
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: reviewersToAdd
            });
            console.log(`Reviewers ${reviewersToAdd.join(', ')} successfully assigned.`);
