name: Checkov Security Scan

on:
  push:
    branches:
      - aws-dev 
  pull_request:
    branches:
      - aws-dev

permissions:
  contents: read

jobs:
  checkov_scan:
    permissions:
      contents: read 
      #security-events: write  # GitHub Advanced Security required for SARIF upload
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.6

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12.2777.0
        id: checkov
        with:
          directory: '.'
          output_format: 'cli'

      - name: Print Checkov Results
        run: echo "${{ steps.checkov.outputs.results }}"  # Print to action output
        
      # --- GitHub Advanced Security Required ---
      #- name: Upload SARIF file (optional) 
      #  if: always()
      #  uses: github/codeql-action/upload-sarif@v3.25.8 
      #  with:
      #    sarif_file: 'results.sarif' 
      # ---------------------------------------- 
