on:
  push:
    branches:
      - aws-dev
  pull_request:
    branches:
      - aws-dev

permissions:
  contents: read

jobs:
  checkov_scan:
    permissions:
      contents: read  # for actions/checkout to fetch code
      # security-events: write  # Commented out as it requires GitHub Advanced Security
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        uses: actions/cache@v4.0.2 # v4.0.2
        with:
         path: |
           ./.github/workflows/
         key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-workflow-${{ github.event_name }}-       

      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.1 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.7 # v4.1.7

      - name: Checkov Scan
        id: checkov_scan
        uses: bridgecrewio/checkov-action@v12.1347.0 # v12.1347.0
        with:
          directory: '.'  # Root directory to scan (adjust if needed)
          output_format: 'json'  # Output format (cli, json, junit_xml, sarif)
          # Add other Checkov configuration options here if necessary

      - name: Save Checkov Results to File
        if: always()
        run: echo "${{ steps.checkov_scan.outputs.results }}" > checkov_results.json

      - name: Extract and Display Passed Checks (If Any)
        if: always()  # Always run, might have no output
        run: |
          echo "Checkov Scan Results (Passed Checks Only):"
          # Filter only passed checks using jq
          jq -r '.results[] | select(.result=="PASSED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true 

      - name: Extract and Display Failed Checks (If Any)
        if: steps.checkov_scan.outcome != 'success'  # Only run if there are failures
        run: |
          echo "Checkov Scan Results (Failed Checks Only):"
          # Filter only failed checks using jq
          jq -r '.results[] | select(.result=="FAILED") | "\(.resource) - \(.check_name) (\(.check_id)): \(.file_path):\(.file_line_range)"' checkov_results.json || true 

      - name: Fail on Checkov Errors (Push Only)
        if: steps.checkov_scan.outcome == 'failure' && !contains(github.event_name, 'pull_request')
        run: exit 1

      # Commented out the step that requires GitHub Advanced Security
      # - name: Upload SARIF file (optional)
      #   if: always()  # Always run this step, even if previous steps fail
      #   uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
      #   with:
      #     sarif_file: 'results.sarif'  # SARIF output file name (adjust if needed)