name: Common Steps

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The working directory'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  setup-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify working directory
        run: pwd

      - name: List root directory
        run: ls -la

      - name: List workflows directory
        run: ls -la ${{ inputs.working-directory }}/.github/workflows

      - name: List scripts directory
        run: ls -la ${{ inputs.working-directory }}/.github/workflows/scripts

      - name: Check if test script exists
        run: test -f ${{ inputs.working-directory }}/.github/workflows/scripts/enforce-branch-sequence-test.sh && echo "File exists" || echo "File does not exist"

      - name: Make scripts executable
        run: chmod +x ${{ inputs.working-directory }}/.github/workflows/scripts/*.sh
