name: Direct Push Protection

on:
  push:
    branches:
      - master
      - staging
      - aws-dev

jobs:
  block_push:
    runs-on: ubuntu-latest
    steps:
      - name: Block Direct Push
        run: |
          echo "Error: Direct pushes to this branch are not allowed. Please use the established PR workflow."
          exit 1