name: GitHub Guardian

on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]
  pull_request_review:
    types: [submitted]

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Enforce Branch Sequence
        if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
        run: |
          protected_branches=('master' 'staging' 'aws-dev')
          if [[ " ${protected_branches[*]} " =~ " ${github.base_ref} " ]]; then
            expected_source_branch=${protected_branches[$(($((for i in "${!protected_branches[@]}"; do if [[ "${protected_branches[i]}" == "${github.base_ref}" ]]; then echo $i; fi; done))+1))]}
            if [[ "${github.head_ref}" != "${expected_source_branch}" ]]; then
              echo "Error: PRs to '${github.base_ref}' must originate from '${expected_source_branch}'."
              exit 1
            fi
          fi

  manage-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Assign Reviewers
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request' 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['GTCrais', 'CTLLaw']
            })

  enforce-approval-rules:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    needs: manage-reviewers # Ensure reviewers are assigned before checking approval
    steps:
      - name: Check Approver
        env: 
          ALLOWED_APPROVERS: GTCrais,CTLLaw
        run: |
          if [[ ! " ${ALLOWED_APPROVERS} " =~ " ${github.actor} " ]]; then
            echo "Error: Only @GTCrais and @CTLLaw are allowed to approve PRs."
            exit 1
          fi
