name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - uses: anishathalye/proof-html@v2.1.3
        with:
          directory: ./
