name: Scorecard supply-chain security

on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: ["master"]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      # security-events: write  # Commented out as it requires GitHub Advanced Security.
      # Needed to publish results and get a badge (see publish_results below).
      # id-token: write  # Commented out as it requires GitHub Advanced Security.
      contents: read
      actions: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0 # v2.8.0
        with:
          egress-policy: audit

      - name: "Checkout code"
        uses: actions/checkout@v4.1.6 # v4.1.6
        with:
          persist-credentials: false

      - name: "Run analysis"
        id: run_analysis
        uses: ossf/scorecard-action@v2.3.3 # v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false  # Set to false to avoid publishing results as it requires GitHub Advanced Security.

      # Commented out steps that require GitHub Advanced Security.
      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      # - name: "Upload artifact"
      #   uses: actions/upload-artifact@v4.3.3 # v4.3.3
      #   with:
      #     name: SARIF file
      #     path: results.sarif
      #     retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      # - name: "Upload to code-scanning"
      #   uses: github/codeql-action/upload-sarif@v3.25.8 # v3.25.8
      #   with:
      #     sarif_file: results.sarif

      - name: Print Scorecard Analysis Results
        if: always()  # Ensure this step runs even if previous steps fail.
        run: |
          echo "Scorecard Analysis Results:"
          cat results.sarif  # Output the results to the console.
