name: Branch Sequence & Permissions Testing

on:
  push:
    branches:
      - main
      - master
      - aws-dev
      - staging
  pull_request:
    branches:
      - main
      - master
      - aws-dev
      - staging
  pull_request_review:
  pull_request_target:

permissions:
  contents: read  

jobs:
  clear-cache:   
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        uses: actions/cache@v4
        with:
          path: |
            ./.github/workflows/
          key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-workflow-${{ github.event_name }}-

  test-branch-sequence:    
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v3.6.0  

      - name: Install tree 
        run: sudo apt-get install -y tree

      - name: Check Script Directory
        run: |
          pwd  
          cd .github/workflows/scripts  
          pwd                         
          ls -la                        
          if [ ! -r "./01-direct-push-master.sh" ]; then  
            echo "Error: Scripts are not readable."
            exit 1
          fi

      - name: Make scripts executable
        run: chmod +x *.sh 

      - name: Run Branch Sequence Tests
        run: |
          for i in {1..10}; do  
            script="0${i}-*.sh" 
            if [ -f "$script" ]; then
              echo "Running: $script"
              ENFORCE_BRANCH_SEQUENCE_FILE="$GITHUB_WORKSPACE/.github/workflows/enforce-branch-sequence.yml" 
              bash "$script" "$ENFORCE_BRANCH_SEQUENCE_FILE" || exit 1 
            else
              echo "Skipping: $script not found."  
            fi
          done

  test-reviewer-permissions:   
    runs-on: ubuntu-latest
    env:  
      PR_CREATOR: automation-bot      
      INVALID_REVIEWER: "4k4xs4pH1r3-2"  

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0 
        with:
          egress-policy: audit
      - name: Checkout Code
        uses: actions/checkout@v3.6.0 
      - name: Install jq 
        run: sudo apt-get install -y jq

      - name: Check Script Directory
        run: |
          pwd  
          cd .github/workflows/scripts 
          pwd                         
          ls -la                        
          if [ ! -r "./07-pr-creation-gtcrais.sh" ]; then 
            echo "Error: Scripts are not readable."
            exit 1
          fi

      - name: Make scripts executable
        run: chmod +x *.sh

      - name: Run Test Cases
        run: |
          for i in {7..10}; do  # Notice the start index is 7 for this job
            script="0${i}-*.sh" 
            if [ -f "$script" ]; then
              echo "Running: $script"
              ENFORCE_BRANCH_SEQUENCE_FILE="$GITHUB_WORKSPACE/.github/workflows/enforce-branch-sequence.yml" 
              bash "$script" "$ENFORCE_BRANCH_SEQUENCE_FILE" || exit 1 
            else
              echo "Skipping: $script not found."  
            fi
          done
