name: Branch Sequence & Permissions

on:
  push:
    branches:
      - main
      - master
      - aws-dev
      - staging
  pull_request:
    branches:
      - main
      - master
      - aws-dev
      - staging
  pull_request_review:
  pull_request_target:

permissions:
  contents: read

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        uses: actions/cache@v2
        with:
          path: |
            ./.github/workflows/
          key: ${{ runner.os }}-workflow-${{ github.event_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-workflow-${{ github.event_name }}-
  
  test-branch-sequence:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v3.6.0

      - name: Install tree
        run: sudo apt-get install -y tree        

      - name: Run Branch Sequence Tests
        run: |
          if [ ! -d "./.github/workflows/scripts" ]; then
            echo "Error: Scripts directory not found."
            exit 1
          fi

          all_tests_passed=true
          for script in \
            ./.github/workflows/scripts/01-direct-push-master.sh \
            ./.github/workflows/scripts/02-direct-push-staging.sh \
            ./.github/workflows/scripts/03-direct-push-aws-dev.sh \
            ./.github/workflows/scripts/04-pr-any-to-aws-dev.sh \
            ./.github/workflows/scripts/05-pr-aws-dev-to-staging.sh \
            ./.github/workflows/scripts/06-pr-staging-to-master.sh; do 
              echo "Running: $script"
              if ! bash "$script"; then
                echo "Error: $script failed. Check the script output for details."
                all_tests_passed=false  
              else
                echo "Success: $script passed." 
              fi
          done

          if [ "$all_tests_passed" = false ]; then
            exit 1
          fi

  test-reviewer-permissions:
    runs-on: ubuntu-latest
    env:  
      PR_CREATOR: automation-bot
      INVALID_REVIEWER: "4k4xs4pH1r3-2"  

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.8.0 
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v3.6.0 

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Test Cases
        run: |
          if [ ! -d "./.github/workflows/scripts" ]; then
            echo "Error: Scripts directory not found."
            exit 1  
          fi

          set -e  

          all_tests_passed=true 
          for script in \
            ./.github/workflows/scripts/07-pr-creation-gtcrais.sh \
            ./.github/workflows/scripts/08-pr-creation-ctllaw.sh \
            ./.github/workflows/scripts/09-add-invalid-reviewer.sh \
            ./.github/workflows/scripts/10-approval-merge-permissions.sh; do
              echo "Running: $script"
              if ! bash "$script"; then
                echo "Error: $script failed. Check the script output for details."
                all_tests_passed=false  
              else
                echo "Success: $script passed." 
              fi
          done

          if [ "$all_tests_passed" = false ]; then
            exit 1
          fi
